#!/usr/bin/env bash
#MISE description="Setting up project"

echo ""
echo "🍜 Setting up project"
echo ""

is_git_worktree=false
if git worktree list | grep -q "$(pwd)"; then
	is_git_worktree=true
fi

# Only run hk install if not in a git worktree
if [ -f .husky/pre-commit ] && [ "$is_git_worktree" = false ]; then
	echo "🔧 Installing Husky git hooks"
	hk install
fi

bun install

echo ""
echo "👍 Done"
echo ""
